services:
  - type: web
    name: bridge-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
